import type { Site } from "../types";
import { detectors } from "./pii";

const name = "Ventanilla";

export const site: Site = {
  code: "co",
  lang: "es",
  locale: "es-CO",
  brand: {
    name,
    tagline: "Lo que necesites del Estado, empieza aquí.",
    notice: "Proyecto independiente. No es un sitio oficial del Gobierno de Colombia.",
    noticeShort: "Proyecto independiente, no es un sitio oficial.",
    disclaimer: "Ventanilla es un proyecto independiente. No es un sitio oficial del Gobierno de Colombia. Las respuestas citan fuentes públicas consultadas a través de Croma.",
    poweredBy: "Datos por",
    handledBy: "Lo atiende",
  },
  meta: {
    title: name,
    chatTitle: `Conversación | ${name}`,
    description: "Respuestas claras sobre trámites, normas y servicios del Estado colombiano, citando solo fuentes oficiales.",
  },
  hero: {
    greeting: "Hola, Colombia",
    subtitle: "Lo que necesites del Estado, empieza aquí.",
    tryPrefix: "Prueba",
    cards: [
      { slug: "pasaporte", title: "Pasaporte", prompt: "¿Cómo saco el pasaporte por primera vez?", alt: "Joven feliz con su pasaporte en una calle soleada", entity: "cancilleria.gov.co", image: "pasaporte" },
      { slug: "cedula", title: "Cédula", prompt: "¿Cómo saco la cédula por primera vez?", alt: "Dos jóvenes muestran su cédula nueva", entity: "registraduria.gov.co", image: "cedula" },
      { slug: "licencia", title: "Licencia de conducción", prompt: "¿Cómo saco la licencia de conducción por primera vez?", alt: "Joven con su licencia junto a un carro", entity: "runt.gov.co", image: "licencia" },
      { slug: "rut", title: "RUT", prompt: "¿Cómo saco el RUT para trabajar como independiente?", alt: "Trabajadora independiente sonríe frente a su computador", entity: "dian.gov.co", image: "rut" },
      { slug: "eps", title: "EPS", prompt: "¿Cómo me cambio de EPS?", alt: "Señora mayor revisa sus documentos de salud con su hija", entity: "minsalud.gov.co", image: "eps" },
      { slug: "empresa", title: "Empresa", prompt: "¿Cómo registro una empresa en la Cámara de Comercio?", alt: "Emprendedor revisa los papeles de su empresa", entity: "rues.org.co", image: "empresa" },
      { slug: "comparendo", title: "Comparendo", prompt: "¿Cómo pago un comparendo de tránsito?", alt: "Conductor consulta su celular en una calle de Bogotá", entity: "simit.org.co", image: "comparendo" },
      { slug: "extranjeria", title: "Extranjería", prompt: "Soy extranjero, ¿cómo saco la cédula de extranjería?", alt: "Amigos de varios países revisan sus documentos en un café", entity: "migracioncolombia.gov.co", image: "extranjeria" },
    ],
  },
  manifesto: {
    lead: name,
    beforeSources: "usa IA\npara darte respuestas simples\nsolo de",
    beforePrivacy: "fuentes\noficiales del Estado. Es gratis,\nno tiene anuncios y",
    afterPrivacy: "protege\ntu privacidad.",
    flag: ["#FCD116", "#FCD116", "#003893", "#CE1126"],
  },
  features: [
    {
      key: "ask",
      title: "Todo el Estado en un solo lugar.",
      body: "Deja de saltar entre portales. Ventanilla reúne trámites, normas y fallos de cientos de entidades en una sola conversación.",
      cta: "Cómo funciona",
      href: "#how-it-works",
    },
    {
      key: "privacy",
      title: "Tu conversación es tuya.",
      body: "No pedimos ni guardamos datos personales. Bloqueamos cédulas, teléfonos y direcciones antes de enviar, y la conversación desaparece al salir.",
      cta: "Sobre tu privacidad",
      href: "#privacidad",
    },
    {
      key: "sources",
      title: "Respuestas claras.\nFuentes oficiales.",
      body: "Cada respuesta cita portales .gov.co y registros públicos como Función Pública, la Corte Constitucional y la DIAN.",
      cta: "Ver las fuentes",
      href: "https://docs.usecroma.com/guides/colombia/funcion-publica",
    },
    { key: "browser", title: "Sin apps para descargar.", body: "Abre Ventanilla desde el navegador de tu celular, tablet o computador.", cta: "Haz una pregunta" },
  ],
  orbit: [
    { label: "DIAN", domain: "dian.gov.co" }, { label: "Registraduría", domain: "registraduria.gov.co" }, { label: "Cancillería", domain: "cancilleria.gov.co" },
    { label: "ADRES", domain: "adres.gov.co" }, { label: "Colpensiones", domain: "colpensiones.gov.co" }, { label: "MinSalud", domain: "minsalud.gov.co" },
    { label: "MinTrabajo", domain: "mintrabajo.gov.co" }, { label: "SENA", domain: "sena.edu.co" }, { label: "ICBF", domain: "icbf.gov.co" },
    { label: "ICETEX", domain: "icetex.gov.co" }, { label: "Migración", domain: "migracioncolombia.gov.co" }, { label: "RUNT", domain: "runt.gov.co" },
    { label: "SIMIT", domain: "simit.org.co" }, { label: "Supersalud", domain: "supersalud.gov.co" }, { label: "SIC", domain: "sic.gov.co" },
    { label: "Supersociedades", domain: "supersociedades.gov.co" }, { label: "Función Pública", domain: "funcionpublica.gov.co" }, { label: "Corte Constitucional", domain: "corteconstitucional.gov.co" },
    { label: "Rama Judicial", domain: "ramajudicial.gov.co" }, { label: "Procuraduría", domain: "procuraduria.gov.co" }, { label: "Contraloría", domain: "contraloria.gov.co" },
    { label: "DANE", domain: "dane.gov.co" }, { label: "DNP", domain: "dnp.gov.co" }, { label: "Colombia Compra", domain: "colombiacompra.gov.co" },
    { label: "MinEducación", domain: "mineducacion.gov.co" }, { label: "MinVivienda", domain: "minvivienda.gov.co" }, { label: "UGPP", domain: "ugpp.gov.co" },
    { label: "Policía", domain: "policia.gov.co" }, { label: "RUES", domain: "rues.org.co" }, { label: "Libreta Militar", domain: "libretamilitar.mil.co" },
  ],
  showcase: ["registraduria.gov.co", "cancilleria.gov.co", "sena.edu.co", "corteconstitucional.gov.co", "procuraduria.gov.co", "policia.gov.co", "dane.gov.co", "ramajudicial.gov.co", "minsalud.gov.co"],
  entities: {
    "gov.co": { name: "Portal del Estado colombiano", short: "GOV" },
    "cancilleria.gov.co": { name: "Cancillería", short: "CA" },
    "registraduria.gov.co": { name: "Registraduría Nacional", short: "RN" },
    "dian.gov.co": { name: "DIAN", short: "DI" },
    "rues.org.co": { name: "RUES", short: "RU" },
    "ccb.org.co": { name: "Cámara de Comercio de Bogotá", short: "CC" },
    "sisben.gov.co": { name: "Sisbén", short: "SI" },
    "dnp.gov.co": { name: "Departamento Nacional de Planeación", short: "DN" },
    "minsalud.gov.co": { name: "Ministerio de Salud", short: "MS" },
    "supersalud.gov.co": { name: "Superintendencia de Salud", short: "SS" },
    "adres.gov.co": { name: "ADRES", short: "AD" },
    "libretamilitar.mil.co": { name: "Libreta Militar", short: "LM" },
    "ejercito.mil.co": { name: "Ejército Nacional", short: "EJ" },
    "corteconstitucional.gov.co": { name: "Corte Constitucional", short: "CC" },
    "ramajudicial.gov.co": { name: "Rama Judicial", short: "RJ" },
    "funcionpublica.gov.co": { name: "Función Pública", short: "FP" },
    "colpensiones.gov.co": { name: "Colpensiones", short: "CP" },
    "mintrabajo.gov.co": { name: "Ministerio del Trabajo", short: "MT" },
    "simit.org.co": { name: "SIMIT", short: "SM" },
    "runt.gov.co": { name: "RUNT", short: "RT" },
    "movilidadbogota.gov.co": { name: "Secretaría de Movilidad de Bogotá", short: "MB" },
    "bogota.gov.co": { name: "Alcaldía de Bogotá", short: "BO" },
    "colombiacompra.gov.co": { name: "Colombia Compra Eficiente", short: "CE" },
    "secop.gov.co": { name: "SECOP", short: "SE" },
    "suin-juriscol.gov.co": { name: "SUIN-Juriscol", short: "SJ" },
    "supersociedades.gov.co": { name: "Superintendencia de Sociedades", short: "SO" },
    "sic.gov.co": { name: "Superintendencia de Industria y Comercio", short: "SC" },
    "icbf.gov.co": { name: "ICBF", short: "IC" },
    "sena.edu.co": { name: "SENA", short: "SN" },
    "mineducacion.gov.co": { name: "Ministerio de Educación", short: "ME" },
    "icetex.gov.co": { name: "ICETEX", short: "IX" },
    "migracioncolombia.gov.co": { name: "Migración Colombia", short: "MC" },
    "policia.gov.co": { name: "Policía Nacional", short: "PN" },
    "procuraduria.gov.co": { name: "Procuraduría", short: "PG" },
    "contraloria.gov.co": { name: "Contraloría", short: "CG" },
    "dane.gov.co": { name: "DANE", short: "DA" },
    "ugpp.gov.co": { name: "UGPP", short: "UG" },
    "minvivienda.gov.co": { name: "Ministerio de Vivienda", short: "MV" },
    "secretariasenado.gov.co": { name: "Secretaría del Senado", short: "SS" },
    "miseguridadsocial.gov.co": { name: "Mi Seguridad Social (MinSalud)", short: "MS", iconFrom: "minsalud.gov.co" },
    "minjusticia.gov.co": { name: "Ministerio de Justicia", short: "MJ" },
  },
  officialSuffixes: [".gov.co", ".mil.co", "rues.org.co", "ccb.org.co", "confecamaras.org.co", "simit.org.co", "sena.edu.co"],
  pii: detectors,
  nav: {
    primary: [
      { label: "Cómo funciona", href: "/#how-it-works" },
      { label: "Privacidad", href: "/#privacidad" },
      { label: "Datos por Croma", href: "https://usecroma.com" },
    ],
    legal: [{ label: "Fuentes y cobertura", href: "https://docs.usecroma.com/guides/colombia/funcion-publica" }],
  },
  ui: {
    askAnything: "Pregunta lo que necesites…",
    describe: "Describe lo que necesitas",
    ask: "Pregúntale a Ventanilla",
    send: "Enviar mensaje",
    stop: "Detener respuesta",
    examples: "Preguntas de ejemplo",
    example: "Ejemplo {n} de {total}: {text}",
    prev: "Ejemplo anterior",
    next: "Siguiente ejemplo",
    play: "Reproducir los ejemplos",
    pause: "Pausar los ejemplos",
    preparing: "Preparando tu respuesta.",
    ready: "Respuesta lista. Hay fuentes y preguntas sugeridas.",
    conversation: "Conversación con Ventanilla",
    messages: "Mensajes",
    copy: "Copiar",
    close: "Cerrar",
    source: "fuente",
    thanks: "¡Gracias!",
    thanksBody: "Tu calificación se queda en tu navegador; no la enviamos a ningún lado.",
    actions: "Acciones del mensaje",
    copied: "Copiado",
    good: "Buena respuesta",
    bad: "Mala respuesta",
    unrate: "Quitar calificación",
    sources: "Fuentes",
    officialSources: "Fuentes oficiales consultadas",
    unverified: "No pudimos verificar esta respuesta con fuentes oficiales en este momento. Confírmala directamente con la entidad antes de actuar.",
    newTab: "se abre en una pestaña nueva",
    menu: "Menú",
    closeMenu: "Cerrar menú",
    followUps: "Preguntas sugeridas",
    piiBlocked: "Quita los datos personales ({labels}) para poder enviar. Ventanilla no necesita tu información para responder.",
    rateLimited: "Hiciste muchas preguntas seguidas. Espera un momento e intenta de nuevo.",
    unavailable: "No pudimos responder en este momento. Intenta de nuevo en unos segundos.",
    flagLabel: "Animar la bandera de Colombia",
    flagDone: "La flecha se convierte en la bandera de Colombia.",
    badges: "Entidades: {list}",
    fingerprint: "Animar la huella",
    fingerprintDone: "Animación completa. Aparece un visto bueno.",
    orbitPlay: "Reproducir animación",
    orbitPause: "Pausar animación",
    star: "Lanzar una estrella fugaz",
    starDone: "Una estrella fugaz cruza el cielo.",
  },
  pending: {
    thinking: ["Pensando…", "Entendiendo tu pregunta…"],
    searching: ["Consultando fuentes oficiales…", "Revisando normas y portales del Estado…", "Buscando la guía oficial…"],
    reviewing: ["Revisando las fuentes…", "Preparando tu respuesta…"],
    longer: ["Esto tarda un poco más…", "Las fuentes oficiales están respondiendo despacio…", "Un momento más…"],
  },
  disclaimers: {
    privacy: {
      title: "Tu privacidad",
      items: [
        {
          heading: "Comparte solo lo necesario",
          body: "Revisamos tu mensaje en el navegador y no lo enviamos si detectamos cédulas, teléfonos, correos, placas o direcciones. Revisa lo que escribes: podemos no detectarlo todo.",
        },
        {
          heading: "Sin rastreo",
          body: "No usamos cookies, analítica ni tu ubicación. Tu dirección IP se queda en nuestro servidor: las fuentes y el modelo de IA solo reciben la pregunta.",
        },
        {
          heading: "Retención mínima",
          body: "No guardamos conversaciones. Las consultas a fuentes públicas se guardan en caché hasta 24 horas, identificadas por un hash, no por el texto.",
        },
      ],
    },
    ai: {
      title: "Cómo funciona la IA",
      items: [
        {
          heading: "Respuestas con fuentes",
          body: "Ventanilla usa IA para encontrar y explicar información de entidades públicas colombianas. Puede omitir detalles o interpretar mal una norma: verifica en la fuente oficial antes de actuar.",
        },
        { heading: "No es un sitio oficial", body: "Ventanilla es un proyecto independiente. No representa al Gobierno de Colombia ni a ninguna entidad." },
      ],
    },
  },
};
